telegram:
  token: # токен бота
  chatId: -1234567890123 # ИД чата для уведомлений
  webhookUrl: # TODO: URL для получения веб-хуков, если не задан, то используется long-poll
  messages:
    online: "✅ {{.Name}} is *online*" # текст сообщения при переходе сервиса в состояние "в сети"
    offline: "❌ {{.Name}} is *offline*: {{.Error}}" # текст сообщения при переходе сервиса в состояние "не в сети"
storage:
  dsn: file://./services.yml
