name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4

      # step 2: set up go
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21"

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go mod download

      # step 4: run test
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
