name: Go

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [master]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4

      # step 2: set up go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      # step 3: run golangci-lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=5m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4

      # step 2: set up go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go mod download

      # step 4: run test
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      # step 5: upload coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
